_target_: src.dataset.WeakLensingDataset

data_dir: /cluster/projects/ska/weak-lensing/data/

n_targets: 2

val_fraction: 0.2
split_seed: 5566

noise_seed: null
ng: 30.0
pixel_size_arcmin: 2.0
standardize: true
standardize_labels: true

img_height: 1424
img_width: 176
in_chans: 1

img_size_h: 178   # 1424 / 8
img_size_w: 22    # 176 / 8
patch_size: 2

reduction: avgpool
pool_stride: 8
conv_channels: 64
conv_layers: 2
conv_stride_h: 4
conv_stride_w: 2
conv_kernel: 3
scattering_J: 3
scattering_L: 8
scattering_order: 2
input_dim: ${reduced_dim:${dataset.reduction},${dataset.img_height},${dataset.img_width},${dataset.in_chans},${dataset.pool_stride},${dataset.conv_channels},${dataset.scattering_J},${dataset.scattering_L},${dataset.scattering_order}}

n_hidden: 2
n_hidden_min: 1
n_hidden_max: 3
hidden_width_min: 128
hidden_width_max: 512
hidden_width_step: 128
