# @package _global_
hydra:
  sweeper:
    params:
      dataset.reduction: choice(avgpool, conv, scattering)
      dataset.pool_stride: range(6, 9)
      dataset.conv_channels: choice(16, 32, 64, 128)
      dataset.conv_layers: range(1, 4)
      dataset.conv_kernel: choice(3, 5, 7)
      dataset.scattering_J: range(2, 4)
      dataset.scattering_order: choice(1, 2)
