# @package _global_
defaults:
  - override /objective: ensemble
  - override /member@model.member: kat

model:
  n_members: 8
  grid_jitter: 0
  member:
    embed_dim: 128
    depth: 7
    num_heads: 2
    mlp_ratio: 4.0
    qkv_bias: true
    drop_rate: 0.0
    proj_drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.027898772130408367
    global_pool: token
    act_init: swish
    weight_init: kan
    stem_channels: 8
    stem_layers: 3

optimizer:
  lr: 0.0028178435672808855
  weight_decay: 0.0015707848547466031

training:
  batch_size: 128
  epochs: 20
  early_stopping: false
  es_patience: 12
  es_min_delta: 0.001
  es_restore_best: true
