# @package _global_
defaults:
  - override /objective: ensemble
  - override /member@model.member: kkan

model:
  n_members: 8
  grid_jitter: 0
  member:
    grid_size: 12
    stem_channels: 3
    stem_hidden_channels: 16
    stem_layers: 2

optimizer:
  lr: 0.0030148818406889907
  weight_decay: 0.0034683764817722493

training:
  batch_size: 16
  epochs: 20
  early_stopping: false
  es_patience: 12
  es_min_delta: 0.001
  es_restore_best: true
